### ISSUE TITLE
Add new diagnosis teams 

### ISSUE THREAD

**Issue by janodvarko** [jgraham/site-report-triage#3]
New target teams handling the diagnosis of triaged issues should be added:

* Performance (there are already user story fields with `diagnosis-team:performance`)
* Accessibility (or a11y?)
* APZ (or perhaps this is already coverd by Layout?)

**Comment by janodvarko** [comment]
I've got requests for also adding "APZ" team

**Comment by jgraham** [comment]
https://github.com/jgraham/site-report-triage/commit/72332f5832433abc09aa848a2c14dcb15795ee9c let me know if there's anything missing there (I haven't done an AMO release yet).

**Comment by janodvarko** [comment]
Works for me, thank you!
